### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by dadgamer89** [lfuelling/esx_drugfarms#10]
hi kinda new to this what is this is it just the building or can we interact with them I don't see anywhere I can interact with them

**Comment by lfuelling** [comment]
Hi, this plugin just adds teleports to the buildings mentioned in the README.

Since the buildings are added by other plugins, they need to be configured in the corresponding plugin (see #6 for details).

To interact with things in the added buildings other plugins are needed.
For example to interact with alcohol bottles in the bikers clubhouse you could use something like [esx_liquor](https://github.com/nabi11/esx_liquor), find out the coordinates of the bottles and add them to the [corresponding config section](https://github.com/nabi11/esx_liquor/blob/master/config.lua#L13).

**Comment by dadgamer89** [comment]
ok I got you so need to build a script or something to make these feel more real got it thanks

**Comment by lfuelling** [comment]
Exactly.
If you decide to write such a script please consider publishing it so others can benefit from it. 
If you instead find such a script, feel free to reply to this issue so I can list it in the README.

I'll close this issue for now, if you have additional questions please reopen it.
